databases:
  - name: micronaut
    databaseName: micronaut_jl7v
    user: micronaut_jl7v_user

services:
  - type: web
    name: storegere
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false