
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development
  user: postgres
  password: Fitzo$95

  
test:
  <<: *default
  database: budget_app_test
  user: postgres
  password: Fitzo$95


production:
  <<: *default
  database: budget_app_production
  username: budget_app
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
